version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kurtum1975
      POSTGRES_DB: mvno_db
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
```

Запуск БД:
```bash
cd D:\APP\MVNO10
docker compose up -d
docker compose ps
